version: '3'
services:
  hysds-thredds:
    hostname: hysds-thredds 
    container_name: hysds-thredds
    image: docker.io/unidata/thredds-docker:latest
    # hide the ports since being proxied by nginx
    #ports:
    #  - "8080:8080"
    volumes:
      - ./tomcat/logs/:/usr/local/tomcat/logs/
      - ./tomcat/content/thredds:/usr/local/tomcat/content/thredds
      - /data/ts:/data/ts 
  hysds-leaflet-ts:
    build: .
    hostname: hysds-leaflet-ts
    container_name: hysds-leaflet-ts
    image: hysds/displacement-ts-server:latest
    # hide the ports since being proxied by nginx
    # ports:
    #  - "8888:8888"
    command: [ "supervisord", "-n" ]
  hysds-nginx:
    hostname: hysds-nginx
    container_name: hysds-nginx
    image: nginx:latest
    ports:
      - "80:8888"
      - "443:443"
    volumes:
      - ./configs/leaflet_ts_proxy.conf:/etc/nginx/conf.d/leaflet_ts_proxy.conf
      - ./configs/certs:/etc/ssl/certs
    links:
      - hysds-thredds
      - hysds-leaflet-ts
